name: 🔀 Sync mirror to Gitee

on:
  push:
    branches:
      - master
  create:

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: github.repository == 'timeTravelCYN/phaser-demo'
    steps:
      - name: mirror
        if: (github.event_name == 'push' || (github.event_name == 'create' && github.event.ref_type == 'tag')) && env.SSH_PRIVATE_KEY
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        uses: wearerequired/git-mirror-action@v1
        with:
          source-repo: 'https://github.com/timeTravelCYN/phaser-demo.git'
          destination-repo: 'https://gitee.com/timetravelcyn/phaser-demo.git'